run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Enable default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused constants, variables, functions and types
    
    # Additional recommended linters
    - gofmt         # Check formatting
    - goimports     # Check import ordering
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - bodyclose     # Check for HTTP response body close
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gofmt:
    simplify: true
  
  revive:
    confidence: 0.8
    rules:
      - name: var-naming
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
  
  gosec:
    # Exclude some rules that might be too strict for development
    excludes:
      - G104 # Audit errors not checked - we use errcheck for this
      - G307 # Deferring unsafe method - often needed for test cleanup

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
  
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true